# common config parameters
navbar_rem_size: 5

# server specific config parameters
aap_webserver1:
  config_demo_value: demo_val1
  other_configs:
    conf1: rh_conf1

aap_webserver2:
  config_demo_value: demo_val2
  other_configs:
    conf1: u_conf1
