# common config parameters
navbar_rem_size: 5

# server specific config parameters
aap_webserver1:
  app_version: rh2-4.0.0_final
  other_configs:
    conf1: rh_conf1

aap_webserver2:
  app_version: rh7-4.0.0_final
  other_configs:
    conf1: u_conf1