# common config parameters
navbar_rem_size: 11

# server specific config parameters
aap_webserver1:
  config_demo_value: demo_val11
  other_configs:
    conf1: conf1_new

aap_webserver2:
  config_demo_value: demo_val22
  other_configs:
    conf1: conf2_new
