# common config parameters
navbar_rem_size: 6

# server specific config parameters
aap_webserver1:
  config_demo_value: test_demo11
  other_configs:
    conf1: conf1_new

aap_webserver2:
  config_demo_value: test_demo22
  other_configs:
    conf1: conf2_new
