# common config parameters
navbar_rem_size: 5

# server specific config parameters
aap_webserver1:
  app_version: redhat-3.0.0_final
  other_configs:
    conf1: rh_conf1

aap_appserver1:
  app_version: ubuntu-3.0.0_final
  other_configs:
    conf1: u_conf1