---
- name: Nginx install playbook
  hosts: webservers
  become: yes
  gather_facts: yes  # Include gathering facts
  tasks:
    - name: checking availability of port 8080 (if available, nginx confs are applied)
      shell:
        cmd: curl -k localhost:8080
      register: port8080check_details
      ignore_errors: yes

    # - name: Checking nginx service
    #   shell:
    #     cmd: systemctl status nginx
    #   register: checking_nginx_service_details
    #   ignore_errors: yes

    - name: Not found nginx scenario, tasks execution
      block:
        - name: yum update
          shell: yum update -y
        - name: install nginx
          yum:
            name: nginx
            state: latest
        - name: start nginx
          service:
            name: nginx
            state: started
          register: nginx_installation_details
      when: port8080check_details is failed

    - name: Checking nginx service status prompt
      debug:
        msg: "Nginx is already set-up in the system"
      when: port8080check_details is succeeded

    - name: Post installation steps tasks execution
      block:
        - name: Copy nginx config to /etc/nginx/conf.d
          # ansible.builtin.copy:
          #   src: "../assets/employee_app_nginx.conf"
          #   dest: /etc/nginx/conf.d
          ansible.builtin.template:
            src: "../templates/employee_app_nginx.conf.j2"
            dest: /etc/nginx/conf.d/employee_app_nginx.conf

        - name: Restart the nginx service
          service:
            name: nginx
            state: restarted

        - name: Allow the firewall the 8080 port
          ansible.builtin.shell:
            cmd: firewall-cmd --add-port=8080/tcp --permanent

        - name: Disable the SELinux for the server (stackoverflow suggestion https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx)
          ansible.builtin.shell:
            cmd: setsebool -P httpd_can_network_connect 1

      when: not (nginx_installation_details.failed | default(True)) and (port8080check_details is failed)
    
