---
- name: Docker install playbook
  hosts: webservers
  become: yes
  tasks:
    - name: Gather facts
      setup:

    - name: Setup yum repository for docker install
      ansible.builtin.shell: "yum install -y yum-utils; yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"

    - name: Docker installation on yum
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Docker service up
      service:
        name: docker
        state: started
