---
- name: Playbook for installing nginx latest to Ubuntu and RHEL
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Checking the OS type
      debug:
        msg: "{{ ansible_facts['os_family'] }}"

    - name: Nginx installation status
      ansible.builtin.shell:
        cmd: systemctl status nginx
      register: nginx_status_details
      ignore_errors: yes

    # Now properly install nginx version
    - name: install nginx (if Debian)
      apt:
        name: nginx
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: install nginx (if RedHat)
      yum:
        name: nginx
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start nginx service (if RedHat)
      shell: systemctl start nginx
      when: ansible_facts['os_family'] == "RedHat"

    # Display os update details
    - name: Display Update results
      vars:
        stdout_task1: "{{ update_rhel_details.stdout if update_rhel_details is defined and update_rhel_details.stdout is defined else 'update_rhel not executed or stdout not available' }}"
        stdout_task2: "{{ update_debian_details.stdout if update_debian_details is defined and update_debian_details.stdout is defined else 'update_debian not executed or stdout not available' }}"
      debug:
        msg:
          - "{{ stdout_task1 }}"
          - "{{ stdout_task2 }}"
