---
- name: Sample Application Undeploy Playbook
  hosts: webservers
  become: yes
  vars_files:
    - ../vars/deploy_sample_app_vars.yml
  tasks:
    - name: Check pm2 job list
      ansible.builtin.shell:
        cmd: |
          export PATH="$PATH:/usr/local/bin"
          pm2 jlist | jq '[.[] | {id: .pid, name: .name}]'
      register: pm2_job_list_details

    - name: Parse pm2 job list as an ansible variable
      ansible.builtin.set_fact:
        pm2_job_list: "{{ pm2_job_list_details.stdout | from_json }}"

    - name: Stop and delete the sample application from pm2 job list (if job exists)
      ansible.builtin.shell:
        cmd: |
          export PATH="$PATH:/usr/local/bin"
          pm2 stop {{ app_pm2_identifier }}
          pm2 delete {{ app_pm2_identifier }}
      when: "app_pm2_identifier in (pm2_job_list | map(attribute='name'))"

    - name: Remove production build
      ansible.builtin.file:
        path: "{{ sample_app_src_dir }}/{{ sample_app_name }}/__production_build"
        state: absent

    - name: Remove .next cache
      ansible.builtin.file:
        path: "{{ sample_app_src_dir }}/{{ sample_app_name }}/.next"
        state: absent

    - name: Read the .env.local file from remote host
      slurp:
        src: "{{ sample_app_src_dir }}/{{ sample_app_name }}/.env.local"
      register: env_file_content

    - name: Remove environment variables which are related to app from /etc/environment
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        state: absent
      loop: "{{ env_file_content['content'] | b64decode | split('\n') }}"
      when: item != ""

    - name: Remove .env.local file from sample app source
      ansible.builtin.file:
        path: "{{ sample_app_src_dir }}/{{ sample_app_name }}/.env.local"
        state: absent