---
- name: Uninstall docker playbook
  # Ubuntu 24.04 LTS, Docker version 27.0.3
  hosts: appservers
  become: yes
  tasks:
    - name: Step1 - Uninstall docker components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
        state: absent

    - name: Step2 - Clear docker data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /var/lib/containerd